services:
  db:
    image: postgis/postgis:16-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nature-urbaine
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
